apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafanabackup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: python-cron-job
            image: vvchik/kasat
            command: ["/bin/sh","-c"]
            args: ["curl -o /tmp/script.py https://raw.githubusercontent.com/TheScreechingBagel/grafanabackup/main/script.py; python /tmp/script.py"]
            envFrom:
              - configMapRef:
                  name: env-configmap
              - secretRef:
                  name: env-secrets
          restartPolicy: OnFailure
