apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafanabackup
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: grafanabackup
            image: python:3.10
            command: ["/bin/sh","-c"]
            args: ["pip install boto3 requests; curl -o /tmp/script.py https://raw.githubusercontent.com/TheScreechingBagel/grafanabackup/main/script.py && python /tmp/script.py"]
            envFrom:
              - configMapRef:
                  name: grafanabackup-configmap
              - secretRef:
                  name: grafanabackup-secrets
          restartPolicy: OnFailure
